name: Deploy Completo (Frontend + Backend)

on:
  workflow_dispatch:

jobs:
  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yml

  deploy-backend:
    needs: deploy-frontend
    uses: ./.github/workflows/deploy-backend.yml
