name: Deploy Backend

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      EC2_SSH_KEY:
        required: true
      EC2_HOST:
        required: true
      EC2_USER:
        required: true
      EC2_PATH:
        required: true

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api/alunos-app

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar arquivos para a EC2
        run: |
          rsync -avz --delete --exclude 'static/fotos/***' . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PATH }}

      - name: Instalar dependências e reiniciar serviço
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.EC2_PATH }}
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart aluno-app
          EOF
